### ISSUE TITLE
Wrong regex used in common name sanitization

### ISSUE THREAD

**Issue by kristian** [guybedford/devcert#6]
In line 9 of the index.ts you have a issue in your regex, which causes no common name to be accepted:

`if (!commonName.match(/^(a-zA-Z0-9|\.){1,64}$/))`

You are missing the `[]` brackets of your character group... Should be:

`if (!commonName.match(/^[a-zA-Z0-9.]{1,64}$/))`

**Comment by guybedford** [comment]
Thanks I've published a 0.4.8 with the fix.

This was added in a rush to fix a "security bug" I was threatened with was being posted. Open source is so broken.

**Comment by kristian** [comment]
> Open source is so broken.

It‘s a blessing and a curse sometimes, fully agreed! Thanks @guybedford for the quick fix though!!
